### ISSUE TITLE
View just my changes and total diff after closing pull request

### ISSUE THREAD

**Issue by marcellustavares** [node-gh/gh#10]

**Comment by protoEvangelion** [comment]
This seems to be out of the scope of this project.

**Node GH** does open the PR using hooks after it submits successfully. That was introduced by here: https://github.com/node-gh/gh/commit/f8481d6212186d0c188c85544f14f83debf158ff

At that point you can just go the "Files changed" tab to see the **total diff**

![image](https://user-images.githubusercontent.com/20076677/32677365-faa687d8-c612-11e7-9def-6f5a84887d33.png)

If you want there are also tools that can open all files that were changed if you want to view them from your editor: https://github.com/jeffcsung/opench

If you feel that this should remain open please let me know :)
