### ISSUE TITLE
Can't create a PULL-REQUEST for a repository inside a Organization

### ISSUE THREAD

**Issue by djalmaaraujo** [node-gh/gh#212]
I tried of many ways to use node-gh with the workflow of my actual company. We don't send pull-requests to other users, we just open a pull-request for the current repository inside a organization.

We don't FORK repositories.
Can node-gh work in that way? 

Am I clear?

**Comment by protoEvangelion** [comment]
Not sure exactly when this was fixed but it works now:

```shell
gh pr -s orgname -t test -b test
```
