### ISSUE TITLE
gh --comment should fire gh-jira comment if the plugin is available

### ISSUE THREAD

**Issue by marcellustavares** [node-gh/gh#250]
Possible usages:

gh --comment 'blah' and it comments the same on every service
or even:
gh all --comment 'blah'

**Comment by protoEvangelion** [comment]
@marcellustavares You would need a way to differentiate between whether or not you would like to comment on an **issue** or a **pr**.

On top of that you would have to specify the **issue #** or the **pr #**.

And the **gh Jira plugin** requires that you pass it the **ticket #** which will differ from both the issue/pr #.

It seems to me not worth it to modify the api to that degree when you can accomplish this in two short cmds.

Please let me know if you are still looking to achieve this.  Would be happy to discuss :+1:
