### ISSUE TITLE
Comment fails when checking out a PR

### ISSUE THREAD

**Issue by robdodson** [node-gh/gh#257]
Whenever I checkout a pr from my upstream remote it looks like gh is trying to post a comment but it always fails.

```
$ gh pr 76 --remote upstream
gh [info] Fetching pull request #76 into branch pr-76
gh [success] ✔
gh [hook] gh pr 76 --comment 'Just started reviewing :)'
gh [error] Command failed:
```

node v0.10.24
gh v1.8.2

**Comment by henvic** [comment]
Fixed with 12fa638060f2c2fa2f34238ca604231b3130bdca.
