### ISSUE TITLE
Track command-line usage

### ISSUE THREAD

**Issue by zenorocha** [node-gh/gh#268]
Nowadays we have three ways of tracking NodeGH usage:

1. [NPM downloads](https://www.npmjs.org/package/gh)

    ![](http://f.cl.ly/items/0r3C0F1o0B0F2R0Y2L0X/Screen%20Shot%202014-03-19%20at%2010.53.29%20AM.png)

2. [Website visits](https://www.google.com/analytics)

    ![](http://f.cl.ly/items/0A3h2G2Y2d041I1n1A2O/Screen%20Shot%202014-03-19%20at%2010.55.55%20AM.png)

3. [GitHub visits](https://github.com/node-gh/gh/graphs/traffic)

    ![](http://f.cl.ly/items/1o011q3g2O3J0l2A0w3x/Screen%20Shot%202014-03-19%20at%2010.56.45%20AM.png)

However we don't know what is the most used command or how often people use certain command.

I've been researching and found out that Yeoman use a package called [insight](https://www.npmjs.org/package/insight) to track command-line interactions and send them to Google Analytics. I think we should do the same.

**Comment by henvic** [comment]
commits ff18be86b17d2f231fa4e0236f665529178ac506, 9bed3a8ad8fd415e46c258ad2c6daded49e509e4, e527c0022eaa9e3799fd1eea579991afcd74cb84, 5dc6b4fc65664dc566c8dadb0fcc72086ecabb23, b8de85c5cd49666855bb4930a5ccf1c6df4e479f, 77d6ba23ce50913acac33280f13c7da9504502ee on the [2.0.x](https://github.com/node-gh/gh/tree/2.0.x) branch implements this feature automatically for all commands using a whitelist best-effort approach.

We anonymize everything that doesn't appear to be a existing valid command / parameter or currently in-use param's hard value (true, false, open, closed, etc, it's retrieved from the relevant command API).

![image](https://cloud.githubusercontent.com/assets/936421/5794981/519012fa-9f63-11e4-8824-4347f02ec71b.png)

**Comment by sindresorhus** [comment]
Nice! Let me know (on the Insight issue tracker) if there's anything that could be improved with [Insight](https://github.com/yeoman/insight) :)

**Comment by zenorocha** [comment]
Awesome, good job @henvic ;D
