### ISSUE TITLE
Use only camelCase pattern

### ISSUE THREAD

**Issue by brunocoelho** [node-gh/gh#273]
There's a lot of snake_case variables, would be nice to add `camelcase` property to `.jshintrc` file.

http://www.jshint.com/docs/options/#camelcase

```
Repo.prototype.clone_ = function(user, repo, repo_url) {
```

```
Repo.prototype.new = function(opt_callback) {
```

**Comment by henvic** [comment]
Changing this to milestone 2.0.0 as I don't want to waste time manually solving conflicts when we merge the 2.0.x branch because of this.

**Comment by protoEvangelion** [comment]
jshint has deprecated the `camelcase` feature.  I will circle back to this soon to see if it would make since to solve this with a combo of [prettier](https://github.com/prettier/prettier) and [eslint](https://eslint.org/docs/rules/camelcase).

**Comment by protoEvangelion** [comment]
Now that we are using TypeScript we can use this rule: https://palantir.github.io/tslint/rules/variable-name/.

There are a lot of warnings when turning on this feature though so it will be quite a bit of a refactoring.

**Comment by protoEvangelion** [comment]
Added to our eslint config.
