### ISSUE TITLE
Improve website with more content

### ISSUE THREAD

**Issue by pedronauck** [node-gh/gh#303]
Hello guys, I was looking the Node GH website and I saw that in Github has a awesome and complete documentation with the api and some other content, but in the website has only few use case.

I think that could be have the site the same content of github or even more. It would be awesome have sections like "api" or "documentation" and would make more integrable with [Dash](http://kapeli.com/dash) and other documentation tools.

Its only a idea. I'll try to making something to help if I can.

**Comment by zenorocha** [comment]
For future references, here are some examples by projects using readme.io

* https://clearbit.com/docs/
* http://brick.mozilla.io/
* http://developers.watsi.org/
* http://docs.heapanalytics.com/
* http://jobboardio.readme.io/
* http://docs.highfidelity.io/
* http://dev.roverlabs.co/
* http://documentation.gamethrive.com/
* http://docs.kickbox.io/

**Comment by protoEvangelion** [comment]
[Electric Docs](https://electricjs.com/) seems like a perfect use case for this

**Comment by protoEvangelion** [comment]
We have improved docs significantly in GitHub readme recently. Going to close this out for now unless anyone has objections.
