### ISSUE TITLE
Display pull request mergeable status on "gh pr" list

### ISSUE THREAD

**Issue by mdelapenya** [node-gh/gh#305]
Sometimes reviewers don't even visit github to see their pending pull requests list, because it's easier executing:

```
gh pr
```
I'd like to see the mergeable status of the pull request, so that reviewer can see if the pull is good to merge or not.

**Comment by henvic** [comment]
Nice idea. I've made some modifications and it already works, but it's not ready for release yet.

@mdelapenya, can you take a look at https://developer.github.com/v3/pulls/#get-a-single-pull-request and please tell me what else you'd find it useful for the --info command to give? Should it show always everything or the --details flag should add something more?

Best regards,
Henrique.

**Comment by mdelapenya** [comment]
Let's start with the mergeable status and the comments on the pull. I guess we can improve later

Thanks @henvic!!

**Comment by mdelapenya** [comment]
Any update on this? :)

**Comment by henvic** [comment]
@mdelapenya I am planning to do this on the weekend.

**Comment by henvic** [comment]
@mdelapenya can you please try the new --info command?

I have not added comments just yet, but will pretty soon.
Sorry for the delay, I couldn't do this until today.

For now --list isn't showing if the pull request is mergeable because it would make --list painfully slow. If GitHub starts to provide this info on their public API I will update. Is that ok?

I have contacted GitHub to ask them if there's any chance they'd add this on the list API method.

**Comment by henvic** [comment]
> Hi Henrique,
>
> Thanks for expressing interest in this -- I'll mention it to the team to consider, but I don't expect it to happen in the near future. Computing the mergeability is a bit expensive, so that's why it's included only when you request a specific pull request (mergeability is computed on demand and in the background):
>
> https://developer.github.com/v3/#summary-representations
>
> https://developer.github.com/v3/pulls/#mergability
>
> I hope this answers your question, but let me know if there's anything else.
>
> Cheers,
> Ivan

> > Just wondering: is there any chance the mergeable flag will be added to the API's list method?
> >
> > Right now it's only exposed with the 'Get a single pull request' method:
> > GET /repos/:owner/:repo/pulls/:number
> >
> > And I have some users claiming it'd be useful for them to see what pull requests are mergeable when listing with this tool I maintain.
> > https://github.com/node-gh/gh/issues/305
> >
> > Best regards,
> > Henrique.

**Comment by mdelapenya** [comment]
Hi Henrique, thanks for the follow-up of this ticket!

I understand the problem, so for me, current --info command could be enough

````
gh pr 445 --info
#445 LPS-55528 Not needed @csierra (20 hours ago)
warning: Not mergeable (dirty)
```

Maybe we could follow a color code for mergeable status, just the same in the real UI.

What do you think?
