### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by faizanqadri** [node-gh/gh#329]
Hello,
Thanks for making this awesome plugin. Kindly let me know how can I resolve this issue: http://prntscr.com/5aa0fs

When I first give gh help then it asks me to login with github and I got successfully logged in and after that when ever I give the command: gh help then it always give me this error:  http://prntscr.com/5aa0vx

Kindly let me know how to resolve this issue?

**Comment by henvic** [comment]
Sorry for taking so long to answer.

We've dropped support for node v0.10 due to problems with polyfills we needed to make gh's development more smooth. If you haven't tried yet, I recommend you try gh now with node v0.12.
