### ISSUE TITLE
Prevent callback hell by using Promises

### ISSUE THREAD

**Issue by zenorocha** [node-gh/gh#338]

**Comment by zenorocha** [comment]
Node.js added native promise support since version `0.11.13` (which is an unstable release). Now that `0.12.0` (which is the latest stable release) is out we need stop supporting older versions in order to use native Promises.

**Comment by henvic** [comment]
Nice. I didn't know about it. This is a great reason to stop immediately supporting prior versions of Node.js.

**Comment by mattdesl** [comment]
Ah.. kinda a bummer :( We are working with a legacy project that is breaking when upgrading to node 0.12, so we are still stuck on an older version.

Why not evaluate an existing Promise polyfill (bluebird etc) rather than forcing users to upgrade Node?

**Comment by henvic** [comment]
@mattdesl, we've tried this approach by the time 0.12 was released but it backfired in several unexpected ways, wasting us lots of time and resources. This is one of the issues reported here, but there are many others: https://github.com/node-gh/gh/issues/349

NodeJS is now a lot more mature and stable (as of 0.12).

We've started to introduce tests and coverage (you can see our last [reports](https://node-gh.github.io/reports) for the master branch). Resources (human and money) are limited. We couldn't do that if we were still supporting 0.10 (it could even impact some other work).

I see many people stuck on node 0.10 relying on gh v1.9.4. If you're one of them, stick to it while you can't upgrade.

If you know of something like n (node version manager) that lets you have many versions of node installed / usable at once, let us know.

**Comment by mattdesl** [comment]
Cool, understandable. :+1:
