### ISSUE TITLE
gh repo under different user/org

### ISSUE THREAD

**Issue by mattdesl** [node-gh/gh#339]
I've been using gh a lot for automating new modules/workflows. Could we add an `--organization` option for `gh re --new` ?

**Comment by zenorocha** [comment]
Have you tried using the `--user` parameter?

**Comment by mattdesl** [comment]
Just tested, the repo was created under my username instead of the organization I passed to --user.

**Comment by tomzx** [comment]
See #353 under 2.0.x.

**Comment by tomzx** [comment]
The `github` library has a `createFromOrg` which would need to be called instead of `create`. It shouldn't be too hard to add support for this.

**Comment by zenorocha** [comment]
Would you like to send a PR @tomzx?

**Comment by tomzx** [comment]
I can look into it when I have some time.

**Comment by mattdesl** [comment]
@zenorocha  I might be able to send a PR, should I target the `2.0 x` branch?

**Comment by zenorocha** [comment]
Yep @mattdesl :)
