### ISSUE TITLE
Initial authorization throws an error attempting to call success on logger

### ISSUE THREAD

**Issue by levbrie** [node-gh/gh#345]
```sh
/usr/local/lib/node_modules/gh/lib/base.js:157
    logger.success('Writing GH config data: ' + configPath);
           ^
TypeError: Object #<Object> has no method 'success'
    at Object.exports.writeGlobalConfigCredentials (/usr/local/lib/node_modules/gh/lib/base.js:157:12)
    at Function.User.authorizationCallback_ (/usr/local/lib/node_modules/gh/lib/cmds/user.js:98:14)
    at /usr/local/lib/node_modules/gh/lib/cmds/user.js:141:26
    at /usr/local/lib/node_modules/gh/node_modules/github/api/v3.0.0/authorization.js:141:17
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/gh/node_modules/github/index.js:782:21)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by dantewang** [comment]
Exactly the same issue on Fedora 21, nodejs v0.10.33, npm 1.3.6 and node-gh installed from npm.

**Comment by zbeekman** [comment]
I'd love to know how to fix this and get it working.

**Comment by tomzx** [comment]
After a bit of tracking down the issue, it comes down to a dependency cycle. `gh.js` needs `logger.js`, which needs `base.js`, which itself needs `logger.js`. `require` will see that `logger.js` has already been required (but is not done so), so it'll just return an empty `logger` object.

To fix this as is, you'd have to remove the dependency on `base.js` in `logger.js`. This means:

- Not depending on `base.getConfig`
- Not depending on `base.getDuration`

**Comment by henvic** [comment]
Hey @tomzx, I've already fixed it on branch 2.0.x a while ago but unfortunately I can't roll a release on npm.

If you want to help us test the future version, remove the current package and use the 2.0.x branch. I'd really appreciate it. `npm install https://github.com/node-gh/gh/tarball/2.0.x`

**Comment by zbeekman** [comment]
I’m not sure if this is just because there’s no npm release rolled yet, but there are a number of dependencies I had to install:
 1. try-thread-sleep
 1. insight

**Comment by tomzx** [comment]
@zbeekman Are you happening to be trying to debug it? It seems that `try-thread-sleep` is a dev dependency of `spawn-sync`. I get a similar error when I try to run `gh` under `node-inspector`.

**Comment by zenorocha** [comment]
We just made a release solving several problems, including this one you just mentioned.

https://github.com/node-gh/gh/releases/tag/v0.10.0

Please grab the latest version from npm by running: `npm -g gh`
