### ISSUE TITLE
TypeError: Cannot read property 'toString' of null when calling config.getNodeModulesGlobalPath

### ISSUE THREAD

**Issue by tomzx** [node-gh/gh#349]
I am on the `2.0.x` branch, after moving from `master` (as suggested in #345). Running io.js `v.1.1.0`, npm `v2.4.1`.

```
E:\gh\bin\gh.js:30
    throw e;
          ^
TypeError: Cannot read property 'toString' of null
    at Object.exports.getNodeModulesGlobalPath (E:\gh\lib\configs.js:31:27)
    at getPlugins (E:\gh\lib\configs.js:193:31)
    at Object.exports.getPlugins (E:\gh\lib\configs.js:211:19)
    at Object.exports.asyncReadPackages (E:\gh\lib\base.js:46:13)
    at Object.exports.checkVersion (E:\gh\lib\base.js:64:13)
    at E:\gh\lib\cmd.js:112:14
    at E:\gh\node_modules\async\lib\async.js:610:21
    at E:\gh\node_modules\async\lib\async.js:249:17
    at iterate (E:\gh\node_modules\async\lib\async.js:149:13)
    at async.eachSeries (E:\gh\node_modules\async\lib\async.js:165:9)
```

**Comment by zbeekman** [comment]
after installing some missing pre-reqs (insight and try-thread-sleep) I get the following error on the 2.0.x branch:

```$ gh --help

/usr/local/lib/node_modules/gh/bin/gh.js:30
    throw e;
          ^
Error: ENOENT, no such file or directory '/var/folders/4t/my3vyzsx7pg80tc_cxhyfc7h0000gp/T/spawn-sync_output_86618db7ee9344988fb7441bd'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at spawnSyncFallback (/usr/local/lib/node_modules/gh/node_modules/spawn-sync/lib/spawn-sync.js:77:27)
    at Object.exports.getNodeModulesGlobalPath (/usr/local/lib/node_modules/gh/lib/configs.js:29:16)
    at getPlugins (/usr/local/lib/node_modules/gh/lib/configs.js:193:31)
    at Object.exports.getPlugins (/usr/local/lib/node_modules/gh/lib/configs.js:211:19)
    at Object.exports.asyncReadPackages (/usr/local/lib/node_modules/gh/lib/base.js:46:13)
    at Object.exports.checkVersion (/usr/local/lib/node_modules/gh/lib/base.js:64:13)
    at /usr/local/lib/node_modules/gh/lib/cmd.js:112:14
    at /usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:610:21
```

**Comment by tomzx** [comment]
@zbeekman, please specify your node/npm version.

**Comment by zbeekman** [comment]
Sorry I forgot that:
```
$ node -v && npm -v
v0.10.36
2.5.1
```

**Comment by tomzx** [comment]
@zbeekman Are you trying to debug `gh`? It seems that `try-thread-sleep` is a dev dependency of `spawn-sync`. I get a similar error when I try to run `gh` under `node-inspector`.

**Comment by henvic** [comment]
Can't believe I messed up this attempt to solve this :(

I've just downloaded 0.10.36 and am trying to figure out what's the issue. Hold on.

**Comment by henvic** [comment]
@zbeekman have you tried to install all dependencies at once with `npm install` and it failed to download insight?

**Comment by zbeekman** [comment]
@tomzx No, I just uninstalled (on Mac OS X Yosemite) gh with `sudo npm uninstall -g gh` and then tried installing with `sudo npm install -g https://github.com/node-gh/gh/tarball/2.0.x`After installing I tried running it `gh --help` and was met with  an error about `try-thread-sleep` So then I uninstalled gh, installed try-thread-sleep, reinstalled the 2.0.x branch of gh and tried to run it again. After that, it complained about `insight` so I uninstalled, again, installed insight and reinstalled. After that it proceeded to run farther, and errored out as shown above.

**Comment by zbeekman** [comment]
@henvic: I installed with: `sudo npm install -g https://github.com/node-gh/gh/tarball/2.0.x` and it didn’t install try-thread-sleep or insight, but I installed them manually with `npm install -g` and gh seemed to run further before throwing an error.

**Comment by tomzx** [comment]
The error about `try-thread-sleep` is most likely due to the 1.0.4 release. See ForbesLindesay/spawn-sync@55a3af4aaea1ca9566f438969f3dc67bfbdd9882.

**Comment by henvic** [comment]
Yeah. I'm on OS X here and saw the same error. By now I've fixed it, I think. But maybe spawn-sync needs to add try-thread-sleep as a dependency, not a devDependency (at least, maybe its resolving wrongly because of it? Dunno).

I'm going to pull some modifications in about 5 minutes.

https://github.com/ForbesLindesay/spawn-sync/pull/9

**Comment by henvic** [comment]
@tomzx, @zbeekman can you please reinstall it and tell me what happens? I've made a few important changes.

**Comment by tomzx** [comment]
Just tried with the latest changes in `2.0.x`. Works without error for me.

**Comment by henvic** [comment]
Do you get a warning? Can you please verify if there's a plugins_path property on your user's .gh.json and pointing to an actual path instead of only ""?

`~/.gh.json | grep plugins_path` should work on a UNIX system. Don't know where it's on Windows.

**Comment by tomzx** [comment]
@henvic I do not have a plugins_path. I guess that is something that should be mentioned in the UPGRADE process.

**Comment by henvic** [comment]
I see it. If you don't need / use any plugins you can set up the "plugins_path" key on your .gh.json file to ""(empty string) to avoid the warnings now: https://github.com/node-gh/gh/commit/65dcf84bdbd104a3fe79bcfcd24bf0ca44c61fec

Yeap. The upgrade process must be improved. After 25th February I'm going to do some work on it. Maybe we need to add the current installed gh version on .gh.json and show update notes and / or run updating scripts when needed.

**Comment by henvic** [comment]
plugins_path is added on setup / gh initialization if the property key doesn't exists on your gh.json file.

It's just a "cached" npm root -g value.

If you set it to empty, it's the same as saying you don't use any plugins.

**Comment by zbeekman** [comment]
@henvic Through `npm install -g` it’s throwing an error at `fs.js:439`
```
$ sudo npm install -g https://github.com/node-gh/gh/tarball/2.0.x

> spawn-sync@1.0.4 postinstall /usr/local/lib/node_modules/gh/node_modules/spawn-sync
> node postinstall


> execSync@1.0.2 install /usr/local/lib/node_modules/gh/node_modules/copy-paste/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2] Native extension compilation successful!
/usr/local/bin/gh -> /usr/local/lib/node_modules/gh/bin/gh.js
gh@1.9.4 /usr/local/lib/node_modules/gh
├── cli-log@0.0.8
├── which@1.0.8
├── truncate@1.0.4
├── userhome@1.0.0
├── open@0.0.5
├── wordwrap@0.0.2
├── async@0.9.0
├── nopt@3.0.1 (abbrev@1.0.5)
├── spawn-sync@1.0.4
├── github@0.2.3
├── update-notifier@0.3.0 (is-npm@1.0.0, string-length@1.0.0, chalk@0.5.1, semver-diff@2.0.0, latest-version@1.0.0, configstore@0.3.2)
├── insight@0.5.2 (object-assign@2.0.0, chalk@0.5.1, lodash.debounce@2.4.1, os-name@1.0.3, tough-cookie@0.12.1, request@2.53.0, configstore@0.3.2)
├── moment@2.9.0
├── handlebars@3.0.0 (optimist@0.6.1, source-map@0.1.43, uglify-js@2.3.6)
├── cli-color@0.3.2 (d@0.1.1, timers-ext@0.1.0, memoizee@0.3.8, es5-ext@0.10.6)
├── inquirer@0.8.0 (ansi-regex@1.1.0, figures@1.3.5, mute-stream@0.0.4, through@2.3.6, readline2@0.1.1, chalk@0.5.1, lodash@2.4.1, rx@2.3.25)
└── copy-paste@1.0.1 (execSync@1.0.2)
```

And here is where I try to run it:
```
$ gh --help

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/var/folders/4t/my3vyzsx7pg80tc_cxhyfc7h0000gp/T/spawn-sync_output_98985b3baf7738753875e4a81'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at spawnSyncFallback (/usr/local/lib/node_modules/gh/node_modules/spawn-sync/lib/spawn-sync.js:77:27)
    at Object.exports.getNodeModulesGlobalPath (/usr/local/lib/node_modules/gh/lib/configs.js:29:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/gh/bin/gh.js:25:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by zenorocha** [comment]
[spawn-sync](https://github.com/ForbesLindesay/spawn-sync) has been causing problems for a while (#208, #218, #347, #266).

For 2.0.0 we should required Node v0.12 (https://github.com/node-gh/gh/commit/81f426ed61948c7f0dcc9756539669b02fb981ab) in order to get rid of `spawn-sync` and things like [execSync](https://github.com/node-gh/gh/search?utf8=%E2%9C%93&q=execSync).

**Comment by tomzx** [comment]
> For 2.0.0 we should required Node v0.12 

(or `io.js`)

:+1:

**Comment by henvic** [comment]
@zenorocha Yeah. I agree we drop support to Node versions prior to 0.12.0, but we were having problems with execSync actually (and only for Node 0.10 as it isn't required for 0.12), not spawn-sync.

spawn-sync seems to work fine now after fixing some issues and I think we better use it for the next 3-6 months to allow people time to move on the new Node version even if they're stuck on 0.10 for some reasons, and then drop support to Node 0.10 entirely.

@tomzx with the news of Node.js Foundation my guess is that io.js will be discontinued.

**Comment by henvic** [comment]
@tomzx, with the news of the Node.js Foundation my guess is that io.js will be discontinued pretty soon.

**Comment by henvic** [comment]
@tomzx, @zbeekman, and anyone who cares about gh: do you guys have any reason why you're still not using 0.12?

We plan to use promises (https://github.com/node-gh/gh/issues/338) and it seems the best we can do right now is stop supporting older versions of Node.

Are you fine with we just dropping support for older versions of the node runtime? And if not, why? How can we help you with it?

By dropping support we'll be able to move on, doing more things, add improvements, and so on, instead of caring about polyfills, etc. This is particularly important because of native promises support (and we intend to solve the current callback hell state) and missing sync operations on Node < 0.12.

The code as it is right now seems to work fine with prior versions, but once we start working on promises it won't anymore unless we add a polyfill (which can be time consuming and prone to errors just like this sync exec. of child process has been for us all).

**Comment by tomzx** [comment]
> @tomzx, with the news of the Node.js Foundation my guess is that io.js will be discontinued pretty soon.

Don't jump too fast to conclusions :wink: 

As for going with 0.12, it all depends on `gh` goals. Are you guys more bleeding edge or do you want to reach a huge userbase by supporting old version of `node.js`? Considering this is a tool more than a library, I would tend to go with the former.

**Comment by zbeekman** [comment]
@henvic I actually think I'm using that version of Node because when I first tried to install node-gh (the 1.x.x or whatever the stable version is that is installed through npm) it issued a warning suggesting that newer versions were not supported. I might be mistaken, though. 

Should I try upgrading Node and then reinstalling node-gh?

**Comment by henvic** [comment]
@tomzx this is why I'm afraid of dropping support of 0.10 till the next 3 months or so, but I guess we just do it and recommend users who can't update to 0.12 to use an older, stable version.

Maybe even creating a tag for the current 2.0.x version just before removing the polyfill and recommending anyone stuck on Node 0.10 who has problems with the official current gh distribution to use it instead.

@zbeekman For some reason unbeknown to me the engine on package.json was limited to 0.12. https://github.com/node-gh/gh/blob/master/package.json#L71

**Comment by zbeekman** [comment]
OK, just switched over to node v0.12.0. Uninstalled node-gh and reinstalled it like so:
```
$ sudo npm install -g https://github.com/node-gh/gh/tarball/2.0.x

> spawn-sync@1.0.5 postinstall /usr/local/lib/node_modules/gh/node_modules/spawn-sync
> node postinstall

-
> execSync@1.0.2 install /usr/local/lib/node_modules/gh/node_modules/copy-paste/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!
/usr/local/bin/gh -> /usr/local/lib/node_modules/gh/bin/gh.js
gh@1.9.4 /usr/local/lib/node_modules/gh
├── cli-log@0.0.8
├── truncate@1.0.4
├── which@1.0.8
├── userhome@1.0.0
├── open@0.0.5
├── wordwrap@0.0.2
├── async@0.9.0
├── nopt@3.0.1 (abbrev@1.0.5)
├── spawn-sync@1.0.5 (concat-stream@1.4.7)
├── github@0.2.3
├── update-notifier@0.3.0 (is-npm@1.0.0, string-length@1.0.0, chalk@0.5.1, semver-diff@2.0.0, latest-version@1.0.0, configstore@0.3.2)
├── insight@0.5.2 (object-assign@2.0.0, chalk@0.5.1, lodash.debounce@2.4.1, os-name@1.0.3, tough-cookie@0.12.1, request@2.53.0, configstore@0.3.2)
├── moment@2.9.0
├── handlebars@3.0.0 (optimist@0.6.1, source-map@0.1.43, uglify-js@2.3.6)
├── cli-color@0.3.2 (d@0.1.1, timers-ext@0.1.0, memoizee@0.3.8, es5-ext@0.10.6)
├── inquirer@0.8.0 (ansi-regex@1.1.0, figures@1.3.5, mute-stream@0.0.4, through@2.3.6, readline2@0.1.1, chalk@0.5.1, lodash@2.4.1, rx@2.3.25)
└── copy-paste@1.0.2 (execSync@1.0.2)
```

Now this is the error I’m encountering:
```
$ gh us
 First we need authorization to use GitHub's API. Login with your GitHub account.
? Enter your GitHub user: zbeekman
? Enter your GitHub password: ********
? Enter your two-factor code: 700814
 [success] Authentication succeed.
 [success] Writing GH config data: /Users/ibeekman/.gh.json
/usr/local/lib/node_modules/gh/node_modules/github/index.js:426
                throw new Error("OAuth2 authentication requires a token or key
                      ^
Error: OAuth2 authentication requires a token or key & secret to be set
    at authenticate (/usr/local/lib/node_modules/gh/node_modules/github/index.js:426:23)
    at Function.User.authorize (/usr/local/lib/node_modules/gh/lib/cmds/user.js:89:17)
    at Function.User.authorizationCallback_ (/usr/local/lib/node_modules/gh/lib/cmds/user.js:101:14)
    at /usr/local/lib/node_modules/gh/lib/cmds/user.js:187:22
    at /usr/local/lib/node_modules/gh/node_modules/github/api/v3.0.0/authorization.js:141:17
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/gh/node_modules/github/index.js:782:21)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by zenorocha** [comment]
We just made a release solving several problems, including this one you just mentioned.

https://github.com/node-gh/gh/releases/tag/v0.10.0

You don't need to fetch code from `2.0.x` branch anymore, just grab the latest version from npm by running: `npm -g gh`

**Comment by zbeekman** [comment]
hallelujah, it works!

**Comment by zenorocha** [comment]
:pray:

**Comment by tomalec** [comment]
With [1.11.4](https://github.com/node-gh/gh/releases/tag/v1.11.4), and
```
$ node -v && npm -v
v0.12.0
2.5.1
```

I still get:

```log

c:\Users\tomalec\AppData\Roaming\npm\node_modules\gh\lib\exec.js:24
        stdout: exec.stdout.toString().trim(),
                           ^
TypeError: Cannot read property 'toString' of null
    at Object.exports.spawnSync (c:\Users\tomalec\AppData\Roaming\npm\node_modules\gh\lib\exec.js:24:28)
    at Object.exports.getNodeModulesGlobalPath (c:\Users\tomalec\AppData\Roaming\npm\node_modules\gh\lib\configs.js:29:23)
    at Object.exports.run (c:\Users\tomalec\AppData\Roaming\npm\node_modules\gh\lib\cmd.js:223:17)
    at Object.<anonymous> (c:\Users\tomalec\AppData\Roaming\npm\node_modules\gh\bin\gh.js:20:26)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

For any gh command :(
