### ISSUE TITLE
Review calls to the github library

### ISSUE THREAD

**Issue by tomzx** [node-gh/gh#354]
While I was trying to fork a repository to an organization, I discovered the payload was using the wrong property name, which was preventing it from working correctly.

I don't know at what point of the github api all the commands were written, but I think it'd be worth doing a code review to make sure nothing is missing or has changed.

Furthermore, it'd be nice to figure out a way to be aware of these changes in the future and possibly in an automated way (see tests).

**Comment by zenorocha** [comment]
SGTM.

**Comment by protoEvangelion** [comment]
Will be fixed by #612. We also have e2e tests that should catch any changes in the @octokit/rest api 😄
