### ISSUE TITLE
Revert docs?

### ISSUE THREAD

**Issue by henvic** [node-gh/gh#361]
https://github.com/node-gh/gh/commit/2b755e73495ab1ba278d4fc8317559a1bb0e4bca reverted https://github.com/node-gh/gh/commit/3dc99fedf6ef1f9c9682ece8b2344f7e098babfb temporarily until we find a better approach to maintain the docs.

@arboliveira rightfully complained the docs were important to him and missed it.

If you also missed having the docs on the README let us know, just so we can find out what's important to you guys.

**Comment by zbeekman** [comment]
The documentation on the README.md is pretty nice, although a ToC would be helpful along with links to jump back to the ToC at the top, as it’s pretty unwieldy. The command line help is OK, but not nearly as helpful as the README.md documentation.

**Comment by henvic** [comment]
@zbeekman the issue we currently have is that maintaining the README.md up-to-date is really annoying, but maybe this is the way to go to keep users happy :(

**Comment by henvic** [comment]
We're considering using a tool to extract the cmds and options, so we can build the docs on a secondary document or website. Any thoughts on that?

**Comment by zbeekman** [comment]
Yeah, I work with compiled languages, mostly Fortran (new and old) and some C, a little python here and there and a lot of shell scripting. I know little about JS or node, but I find the ideal solution is to maintain the documentation along with the source code, and have it extracted and generated automatically. Think literate programming or ROBODoc/DOXYGen or [FORD](https://github.com/cmacmackin/ford). I know Emacs org-mode has tools for literate programming, I seem to remember there was a way to do it with ASCIIDoc but that’s as far as my knowledge takes me.

Good luck, and thanks for the fixes!

**Comment by protoEvangelion** [comment]
Related issue https://github.com/node-gh/gh/issues/303

**Comment by protoEvangelion** [comment]
Closing to continue discussion on this issue: https://github.com/node-gh/gh/issues/303
