### ISSUE TITLE
latest update fails during installation

### ISSUE THREAD

**Issue by rotty3000** [node-gh/gh#362]
```
]$ sudo npm update -g gh
> execSync@1.0.2 install /usr/lib/node_modules/gh/node_modules/copy-paste/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2] Native extension compilation successful!

> spawn-sync@1.0.5 postinstall /usr/lib/node_modules/gh/node_modules/spawn-sync
> node postinstall


/usr/lib/node_modules/gh/node_modules/spawn-sync/postinstall.js:38
      throw err;
            ^
Error: Command failed: npm ERR! Error: EACCES, open '/home/rotty/.npm/spawn-sync/1.0.5/package.tgz'
npm ERR!  { [Error: EACCES, open '/home/rotty/.npm/spawn-sync/1.0.5/package.tgz']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/rotty/.npm/spawn-sync/1.0.5/package.tgz' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "--production"
npm ERR! cwd /usr/lib/node_modules/gh/node_modules/spawn-sync
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path /home/rotty/.npm/spawn-sync/1.0.5/package.tgz
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open '/home/rotty/.npm/spawn-sync/1.0.5/package.tgz'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/lib/node_modules/gh/node_modules/spawn-sync/npm-debug.log
npm ERR! not ok code 0

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

npm ERR! spawn-sync@1.0.5 postinstall: `node postinstall`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.5 postinstall script.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "update" "-g" "gh"
npm ERR! cwd /home/rotty/workspace/blade/gradle/blade.portlet.actioncommand
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by rotty3000** [comment]
I had to revert back to 1.9.4 via `sudo npm install -g gh@1.9.4`

**Comment by rotty3000** [comment]
things I tried:

- changed from the old http://www.ubuntuupdates.org/ppa/chris_lea_nodejs ppa to the new https://github.com/joyent/node/wiki/installing-node.js-via-package-manager

same result.

**Comment by TheBrockEllis** [comment]
I also had the same issue with the spawn-sync package throwing errors. Installing an older version as @rotty3000 suggested seemed to get it installed again. I can provide any debugging information if needed.

**Comment by zenorocha** [comment]
Investigating.

**Comment by zenorocha** [comment]
This issue has already been reported on https://github.com/ForbesLindesay/spawn-sync/issues/11.

**Comment by zenorocha** [comment]
I just released a [new beta version](https://github.com/node-gh/gh/releases/tag/v2.0.0-alpha) which should fix these problems. In order to use it, you'll need NodeJS `0.12.0`.

**Comment by zenorocha** [comment]
@rotty3000, this should be fixed now, please update by running: `npm i gh -g`

**Comment by rotty3000** [comment]
Does it still depend on a new version of nodejs? Because there isn't a new
version released yet in the official nodejs deb repos. It's still v0.10.36.
So maybe I'll wait until that time.

**Comment by zenorocha** [comment]
Not even here? http://nodejs.org/dist/v0.12.0/

**Comment by rotty3000** [comment]
Not when you use a sane OS which is based on package management!

https://github.com/joyent/node/wiki/installing-node.js-via-package-manager

**Comment by dantewang** [comment]
@zenorocha using Fedora here, neither fedora official repo nor nodesource's fedora repo provides 0.12.0. I removed the package and downloaded the binary distribution from nodejs.org.

Maybe it's better to manage nodejs with `nvm` instead of the package manager.

**Comment by zenorocha** [comment]
Indeed @dantewang. Either `nvm` or `n` do a pretty good job in managing different NodeJS versions.

**Comment by rotty3000** [comment]
By following the latest information about installing node.js in linux we can resolve the issue:

See https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories

**Comment by ForbesLindesay** [comment]
The latest version of spawn-sync should be much more resilient (even on older versions of node.js).  If anyone was struggling with this issue I'd encourage them to have another go.
