### ISSUE TITLE
cannot submit PR from a branch named "feature/hello"

### ISSUE THREAD

**Issue by vvo** [node-gh/gh#368]
Using git flow, I have branches named "feature/hello" but the getCurrentBranch() breaks it to "hello", thus I am unable to use node-gh with branch having slashes in names.

**Comment by henvic** [comment]
Thanks for your reporting and sorry for the delay in making the necessary changes. I'll be releasing an update with this fix and a few others in a ~3 hours.

**Comment by vvo** [comment]
AWESOME!
