### ISSUE TITLE
Add gulp bump task

### ISSUE THREAD

**Issue by henvic** [node-gh/gh#371]
- It should have a pre-bump step
- If pre-bump fails, bump is canceled.
- the pre-bump step is compromised of an array of commands to be run before the bump
- if any pre-bump command exits with a non-zero status code, the bump fails
- pre-bump command can be anything such as a continuous integration (CI) procedure to lint code, run tests, compare test complexity with previous one, etc.
- bumps might have customized message (or should it be a pre-bump step?)

This bump command may even be worth of a sole micro project on its own.

**Comment by protoEvangelion** [comment]
@henvic It looks like there is a project that implements this: https://www.npmjs.com/package/gulp-bump

Please let me know if I am mistaken or if you think it would be worth it to implement this.
