### ISSUE TITLE
version 1.11.3 fails to fetch new PRs

### ISSUE THREAD

**Issue by gamerson** [node-gh/gh#373]
Just updated to latest version 1.11.3 and I can list the available PRs using 
```
gh pr
```
but when I try to fetch one using
```
gh pr 354
```
it simply outputs nothing, no fetch or branch creation and no error output to the console.

I'm using Ubuntu 14.04 and I've manually updated my nodejs install to 0.12 using npm and "n" node manager as described here: https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version/480642#480642

**Comment by gamerson** [comment]
I reverted to 0.9.4 via ```sudo npm install -g gh@1.9.4``` and its working again.

**Comment by henvic** [comment]
Hi @gamerson,

I'd appreciate if you go back to the latest version and try to provide the following info for me:
1. show me the output of `gh --version`
2. show me the output of `npm list -g --depth=0 | grep gh`
3. try `gh pr 354 --verbose` and tell us what happens
4. let me know if the pull request exists for your current user on GitHub
5. do you have the gh-jira plugin installed? If you do, are you using a repo that uses Jira or GitHub issues?
6. tell me the exit code of the gh process: `echo $?` just after the process is run


Thanks.

**Comment by henvic** [comment]
@gamerson I've failed to reproduce your issue.

**Comment by gamerson** [comment]
Sorry Henrique, I'll try to reproduce again today and give you those error
logs you asked for.

On Thu, Mar 12, 2015 at 4:01 AM, Henrique Vicente <notifications@github.com>
wrote:

> @gamerson <https://github.com/gamerson> I've failed to reproduce your
> issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/node-gh/gh/issues/373#issuecomment-78358629>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by mdelapenya** [comment]
Hey @gamerson, it's currently working for me on Mac:

node --version:   v0.12.0
gh -v:   gh 1.11.3

**Comment by gamerson** [comment]
Hey @henvic Sorry for the delay, I finally tried to reproduce the issue, but this time I just keep my nodejs 0.10 install (didn't upgrade to 0.12) and now things seem to be working ok with the latest 1.11.4 and things seem to be working now.  sorry for the noise.

**Comment by henvic** [comment]
It's ok, Gregory. Thank you for your feedback!


PS: I don't get how gh 1.11.4 is working with 0.10 because gh is now
backwards incompatible with node < 0.12 (or 0.11 if you count unstable
versions). Maybe you're using node 0.12.0 actually.

Henrique Vicente
https://henvic.github.io/
https://github.com/henvic
http://flickr.com/photos/henriquev/
