### ISSUE TITLE
PR merge and rebase aren't working

### ISSUE THREAD

**Issue by zenorocha** [node-gh/gh#377]
I've added couple commits to this `andrea` branch and when I tried to merge it with `site` branch I got this error:

![screen shot 2015-03-20 at 3 06 03 pm](https://cloud.githubusercontent.com/assets/398893/6757812/b078b158-cf12-11e4-974b-ef2facb15ab7.png)

**Comment by RafaelLucio** [comment]
Hi, I have similar problem, when I try pull request this error is returned

rafaellucio -> myFolder(86047684_I18N)$ gh pr -s myProject -b Branch -t 'test'
Submitting pull request to @myProject
Everything up-to-date
fatal: Can't submit pull request. undefined

My node-gh version is: gh 1.11.4

This bug occured when I updated for latest version of node-gh

**Comment by henvic** [comment]
@zenorocha, I've noticed you forgot to add the pull request number.

Anyways, I've added an error feedback.

@RafaelLucio, your error is hard to debug, but I'm working on improving it as well.
