### ISSUE TITLE
Is it possible to not open browser after issue creation?

### ISSUE THREAD

**Issue by kennethlynne** [node-gh/gh#382]
I only want to create issues from the CLI, and I really do not like the interruption of the browser opening the issue

**Comment by kennethlynne** [comment]
How do I create a global config? 

https://github.com/node-gh/gh/blob/master/lib/configs.js

**Comment by henvic** [comment]
You can edit your ~/.gh.json and remove the hook issue.new `gh is --browser --user {{options.user}} --repo {{options.repo}} --number {{options.number}}`.

If you ever have your .gh.json deleted, you'll have to manually reconfigure by rewriting this config file. Sorry, but we're still looking on how to improve this.
