### ISSUE TITLE
Silent mode for actions 

### ISSUE THREAD

**Issue by lapanoid** [node-gh/gh#387]
Could you disable this 
[hook] gh is --browser --user lapanoid --repo package-update --number 3
with some -s --silent flag?
When I make several actions I am forced to go in browser which is really inconvinient.

**Comment by henvic** [comment]
Hey @lapanoid,
what do you expect the --silent flag to do? Disable all hooks a command has?

Did you know you can edit the hooks for a given command on your ~/.gh.json?

Let me know what you think so we can find out what's the best way to improve gh.

**Comment by lapanoid** [comment]
Hello @henvic ,
No I did not knew it, thanks! But disabling hooks with flag would be nice too. --silent feel natural as for me - user just want to perform action without any other side effects.
