### ISSUE TITLE
gh re: mixing --user and --list and private doesn't seem to work as expected

### ISSUE THREAD

**Issue by wkoszek** [node-gh/gh#401]
Company I work for: twinprime. They have a user "twinprime" owning some private repos.
I'm also a part of "NetFPGA" organization.

I do:

gh re --user twinprime --list --type private

And I see NetFPGA repositories. I think it wrong.

Not only that, but I also see something that seems to be private repos of people in NetFPGA organization.

I'd expect to only get private repos of "twinprime".

**Comment by tomzx** [comment]
Hello @wkoszek,

You may want to try 1.11.10 which contains https://github.com/node-gh/gh/commit/7b9cd1a2b31d6dcf60757c6ff975677570f719dc.
