### ISSUE TITLE
Listing a PR created by a user

### ISSUE THREAD

**Issue by ahmedelgabri** [node-gh/gh#417]
I dunno what I'm doing wrong, but I can't get to list all the PRs that are open in a repo by a user.

I tried all of these with no luck, but if you replace the `-u <username>` and use `--me` it works.

``` sh
$ gh pr -l -u <username> 
$ gh pr -l -u <username> -r <repo>
$ gh pr -l -u <username> --org <org-name> -r <repo>
```

**Comment by protoEvangelion** [comment]
The `--user` flag is intended to function as a github user.

So if you type `gh pr -l -u ahmedelgabri -r dotfiles` it is going to look up PRs @ https://github.com/ahmedelgabri/dotfiles

Although we don't currently have a way to filter a list of PRs by a user, you do have these filtering options: https://github.com/node-gh/gh#2-list.

_Is that what you are looking for?_

**Comment by ahmedelgabri** [comment]
Thanks @protoEvangelion for the comment but I don't use `gh` anymore _(maybe I'll give it a try again)_ 

I think this was maybe an issue 2 years ago but maybe was fixed now, anyway thanks again for the help!
