### ISSUE TITLE
repo --list limited to 100 projects

### ISSUE THREAD

**Issue by lirazsiri** [node-gh/gh#418]
I have more than 100 projects but node-gh doesn't list them.

 $ gh re --list --type public | wc -l
 100

**Comment by henvic** [comment]
Hey @lirazsiri,

when you pass the public flag you only get the public repositories you have on your GitHub account.

I have just browsed to your [repositories tab](https://github.com/lirazsiri?tab=repositories) and it seems you only have 15 repos, is that right? The current limit is 100 for pull requests / repos, but it was the default (100) before. Reference:
* [gh pr -a doesn't work well #413](https://github.com/node-gh/gh/issues/413)
* [Lift the amount of results for listing pull requests and repos](https://github.com/node-gh/gh/commit/e80ea62bc62f552dc96e1c566345b8f9c1c6e4df)

Maybe you are using a outdated version of gh.

**Comment by timdp** [comment]
Does this also apply to org repos? `gh re -l -o zentrick | wc -l` gives me 100 which is incorrect. The output does contain both private and public repos so it's purely the pagination that seems to be broken. This is with gh 1.12.8.

**Comment by henvic** [comment]
Related: https://github.com/node-gh/gh/issues/438

**Comment by protoEvangelion** [comment]
Should be fixed by: 3cc4366
