### ISSUE TITLE
Support for git flow

### ISSUE THREAD

**Issue by mdelapenya** [node-gh/gh#422]
When fetching pull requests, it uses the PR ID as name (pr-id), but git flow could use the feature/my-branch, where feature is a parametrised token defined in the git flow workspace.

If you want to use git flow to merge branches, as the branch is named pr-id, the command:

```
git flow feature list
```

won't find the branch.

Just renaming the branch pr-id to feature/pr-id will work

**Comment by mdelapenya** [comment]
If I rename the **pr-X** to **feature/pr-X**, and then try to submit the pull to an user, then this error is thrown:

```
gh pr -s USER -D "MESSAGE"
Submitting pull request to @USER
error: src refspec pr-feature/X does not match any.
error: failed to push some refs to 'GIT_REPO-URL'
/usr/local/lib/node_modules/gh/lib/exec.js:54
        throw err;
              ^
```

**Comment by protoEvangelion** [comment]
@mdelapenya this should be fixed by: https://github.com/node-gh/gh/commit/f07338961d68337e230e78feed5a2504d34e407a Please let me know if you are still having issues.
