### ISSUE TITLE
Add schema definition to rest-api-client

### ISSUE THREAD

**Issue by henvic** [node-gh/gh#423]
And maybe make it an external, independent, package.

**Comment by protoEvangelion** [comment]
@henvic I know that it has been a while since you opened this. I am not sure what the purpose of this would be.

Are you think of something like: https://restfulapi.net/json-schema/

And the benefit would be for plugins using our rest-api-client?

**Comment by henvic** [comment]
Hi @protoEvangelion,

Thank you for the work you have been doing here. I love it.

I was indeed thinking about a way to validate responses from the API before consuming. I'm not sure how I should approach this now if I were to work on it, and perhaps the right call would be to close it (this should be up to you, as you've taken ownership of the project).

PS: with strongly typed programming languages such as Go, this would be a lesser problem (though it still happens, obviously).

**Comment by protoEvangelion** [comment]
Thanks for clarifying. The github api package now @octokit/rest has really improved their TypeScript definitions. Now that we are using TypeScript we can check parameters really easily, so this shouldn't be a problem. And on top of that, TypeScript with VS Code is a match made in heaven!
