### ISSUE TITLE
Browser-less mode

### ISSUE THREAD

**Issue by rachidbch** [node-gh/gh#424]
When i create a repo from the cli my browser is opened on the newly created repo in GitHub.
Is it possible to avoid this last step so as to use gh in compelte browser-less mode?
I've seen the "--browser" boolean parameter
I've tried to call "gh re --browser false ..." , "gh re --browser no ..." and even tried to tweak the .gh.json so as to not having the --browser option used, it allways ends with the browser open.

I'm i missing something ?

thx for the good work

**Comment by henvic** [comment]
Hey @rachidbch,

I think I just solved your issue, but can you please provide examples of complete commands so I can try and confirm that it is indeed fixed for every case?

Let me know so I can try it and release a new minor version with the changes you requested.

**Comment by henvic** [comment]
When you pass the --browser false parameter the browser should never open.

**Comment by rogosher** [comment]
This may warrant a new issue, but might be resolved here. Is there a way to pass to `gh` the browser you would like to use so lynx or another terminal browser can be used?

**Comment by rachidbch** [comment]
Hi @henvic sorry to come back so late.
I've just update gh to 1.12.6 version and checked again.
Actually the [this change](https://github.com/node-gh/gh/commit/824986179627cd736703c8a5d524b8d8e0a4b813) didn't do the trick and i still have the same behaviour.

My command is : "gh re --browser false --new foo"

I put a trace message in the function you modified (payload in 'lib/cmds/repo.js') and it isn't executed at all ...

please let me know what i'm missing.

thanks for you help
