### ISSUE TITLE
[Docker]: Issues running in a Container: TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by prologic** [node-gh/gh#425]
So I tried to Dockerize this tool and ran into a few issues:

Example run:

``` #!bash
$ gh help
? May gh anonymously report usage statistics to improve the tool over time? Yes
readline.js:924
            throw err;
            ^

TypeError: Cannot read property 'toString' of null
    at Object.exports.spawnSync (/usr/lib/node_modules/gh/lib/exec.js:29:28)
    at Object.exports.getCurrentBranch (/usr/lib/node_modules/gh/lib/git.js:149:20)
    at /usr/lib/node_modules/gh/lib/cmd.js:186:62
    at /usr/lib/node_modules/gh/node_modules/async/lib/async.js:726:13
    at /usr/lib/node_modules/gh/node_modules/async/lib/async.js:52:16
    at /usr/lib/node_modules/gh/node_modules/async/lib/async.js:269:32
    at /usr/lib/node_modules/gh/node_modules/async/lib/async.js:44:16
    at /usr/lib/node_modules/gh/node_modules/async/lib/async.js:723:17
    at /usr/lib/node_modules/gh/node_modules/async/lib/async.js:167:37
    at /usr/lib/node_modules/gh/lib/cmd.js:159:13
```

`$HOME/bin/gh`:

``` #!bash
$ cat bin/gh
#!/bin/bash

eval $(docker-machine env dev)
docker run -i -t --rm prologic/gh "${@}"
```

`Dockerfile`:
$ cat tmp/dockerfiles/gh/Dockerfile
FROM alpine

ENTRYPOINT ["gh"]
CMD []

RUN apk -U add nodejs
RUN npm install gh -g

```
```

**Comment by henvic** [comment]
Hello @prologic,
sorry for taking too long to answer you.

It seems to be a problem with the [async package](https://www.npmjs.com/package/async).

By the way, why is it that you want to Dockerize this tool? Is it for running it sandboxed for security reasons?

Please let me know more so I can see if it interests me and if it does, I can try to find some time to play with it and try to fix the the dependency.

**Comment by prologic** [comment]
I often find it easier to sandbox NodeJS applications; yes.

**Comment by protoEvangelion** [comment]
@prologic I know it's been a while since you opened this, but were you able to find a workaround for this?

I just recently took out the `insight` package so once we release the new version, this should be fixed.

**Comment by prologic** [comment]
Thanks!

**Comment by ojacques** [comment]
Thanks to @protoEvangelion changes, one can create a Docker container with gh like so:
```Dockerfile
FROM node:9.4.0-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache git

# Install gh
RUN npm install -g git+https://git@github.com/node-gh/gh.git
```
