### ISSUE TITLE
Listing all issues nested under the repository name (like in the example)

### ISSUE THREAD

**Issue by dsifford** [node-gh/gh#426]
Hi there.

So I just installed this (strong work, so far I'm really digging this). 

My question is, in the example video, when the person types `gh is -la`, all issues are listed and are nested under the repository it came from. 

When I try that command, it does not produce the same output. 

Any tips?

Thanks again!

**Comment by eduardolundgren** [comment]
I have also noticed a different behavior with this command. /cc @henvic

**Comment by dsifford** [comment]
To add an addendum to this:

Calling `gh is -la` also lists every issue as being created "a few seconds ago"

**Comment by protoEvangelion** [comment]
The timestamps are correct but I am noticing that it is not clear which repository an issue comes from.

Also, 'No issues.' is being printed out numerous times which doesn't make sense.

We will tackle this here: #613
