### ISSUE TITLE
"message":"Not Found","documentation_url":"https://developer.github.com/v3"

### ISSUE THREAD

**Issue by jrschumacher** [node-gh/gh#439]
```
> $ gh pr --submit jrschumacher                                                                                           [±codeship-badge ✓]
Submitting pull request to @jrschumacher
Everything up-to-date
{ [Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}]
  message: '{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}',
  code: 404 }

```

Version `gh 1.12.4`

**Comment by jrschumacher** [comment]
```
> $ gh pr --submit jrschumacher --verbose                                                                                 [±codeship-badge ✓]
DEBUG: ENOENT: no such file or directory, open '/Users/ryan/Projects/outfit/web/.gh.json'
DEBUG: ENOENT: no such file or directory, open '/Users/ryan/Projects/outfit/web/.gh.json'
DEBUG: spawnSync: git config --get remote.origin.url
DEBUG: spawnSync: git symbolic-ref --short HEAD
Submitting pull request to @jrschumacher
DEBUG: spawnSyncStream: git push origin codeship-badge
Everything up-to-date
DEBUG: spawnSync: git log -1 --first-parent --no-merges --pretty=%s codeship-badge --
{ [Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}]
  message: '{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}',
  code: 404 }
```

**Comment by rabross** [comment]
I'm seeing the same issue

**Comment by henvic** [comment]
Hey guys,
this question might seem crazy, but are you authorized in NodeGH with the same user you have access to the private repos? Thanks.

**Comment by rabross** [comment]
Hi henvic. Yes same user.

**Comment by JacobBennett** [comment]
By Authorized, you mean with a personal access token correct?

**Comment by henvic** [comment]
@JacobBennett, yes.

**Comment by rogeriopvl** [comment]
Same issue here. Trying to PR a private repo and logged in with a user account with access to that repo.

**Comment by obazoud** [comment]
Same issue here. Trying to PR a private repo.

**Comment by M1chaelTran** [comment]
same issue

**Comment by zetta** [comment]
Same issue for me 
`gh 1,12.8`

**Comment by petemoore** [comment]
Did anyone get to the bottom of this? :/

**Comment by CharlonTank** [comment]
same issue please !

**Comment by maoo** [comment]
Just stumbled on this issue while pushing a new release of my node project (from Travis CI) using https://github.com/semantic-release/semantic-release . For me the issue was a 403 (wrong GH_TOKEN), but Github (for security reasons) masked it as a 404 ; you can read more on https://developer.github.com/v3/#authentication

HTH

**Comment by magic-madrigal** [comment]
Same Issue:
I can view my private repos using `gh re --list --type private` but unable to submit a PR.

gh -v 1.12.8

**Comment by holms** [comment]
And no one to solve yet?

**Comment by shreyansvm** [comment]
I'm seeing the same issue while creating a new repository. 

```
MyProjects$ curl -u "shreyansvm" https://api.github.com/users/repos -d '{"name":"webHacks"}'
Enter host password for user 'shreyansvm':
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

Same issue while creating a private repo as well.

```
MyProjects$ curl -u "shreyansvm" https://api.github.com/users/repos -d '{"name":"webHacks", "private":"true"}'
Enter host password for user 'shreyansvm':
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
MyProjects$
```

**Comment by pkra** [comment]
FYI I had the same problem while trying to create PRs for a private repo of an organization. Specifying `--submit ORGNAME` solved this for me (I got this idea from https://github.com/node-gh/gh/issues/212#issuecomment-344075822).

**Comment by protoEvangelion** [comment]
It seems most likely that this issue can be resolved by the comment from @maoo

Also, thanks @pkra for linking that!

If the above doesn't solve your problem, please make sure you have `origin` as one of your remotes because we use that as the default basis for sending PRs from.

Then you can try sending PRs either to the private repo itself or a fork of the repo like this:

```shell
gh pr -s ORG_OR_USER
```

I send PRs nearly every week successfully to private repos this way.

If these don't solve your problems I will be happy to reopen.

**Comment by Bhupi2508** [comment]
Hi guys, this is Bhupendra Singh, from Jaipur...
This is common problem for all the students when we create API for create branch in github.....

{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}

for solve this error during create repository in Github.....
first create a personal token in Github=>setting=>developerOption=>generatePersonalToken...
after then...
first  hit the API...(get)
1.  https://api.github.com/repos/<your login name>/<Your Repository Name>/git/refs/heads
after hit this API you got a response which is like ======>
Response => {
[
    {
        "ref": "refs/heads/<already present branch name for ref>",
        "node_id": "jkdhoOIHOO65464edg66464GNLNLnlnnlnlna==",
        "url": " https://api.github.com/repos/<your login name>/<Your Repository Name>/git/refs/heads/<already present branch name for ref>",
        "object": {
            "sha": "guDSGss85s1KBih546465kkbNNKKbkSGyjes56",
            "type": "commit",
            "url": " https://api.github.com/repos/<your login name>/<Your Repository Name>/git/commits/guDSGss85s1KBih546465kkbNNKKbkSGyjes56"
        }
    }
]
}

after complete this process again hit api...(Post)
2.  https://api.github.com/repos/Bhupi2508/Test/git/refs....
and send data in JSON format like that =>
{
    "ref": "refs/heads/<new branch name>",
    "sha": "4661616ikgohlKIKHBK4634GRGSD66"
}

THEN YOU CREATE A BRANCH IN GITHUB bY APIs

**Comment by ezappata** [comment]
> ```
> > $ gh pr --submit jrschumacher                                                                                           [±codeship-badge ✓]
> Submitting pull request to @jrschumacher
> Everything up-to-date
> { [Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}]
>   message: '{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}',
>   code: 404 }
> ```
> 
> Version `gh 1.12.4`

https://github.com/node-gh/gh/issues/439#issue-151143849
