### ISSUE TITLE
Use for Enterprise 

### ISSUE THREAD

**Issue by NizarYousri** [node-gh/gh#442]
How can I use this tool with Enterprise user - need more details

**Comment by NizarYousri** [comment]
I can't provide password for the tool - only access token

**Comment by henvic** [comment]
Hi, I have just noticed there isn't a token-based authentication workflow as of now.

But if your credentials are set, it works.

"github_token": "your-token",
    "github_user": "henvic",

For example, say my token is FE012345ABCD6789.

I can add:

```json
"github_user": "henvic",
"github_token": "FE012345ABCD6789"
```

to my .gh.json (for example, for the global, ~/.gh.json on Unix).

Let me know if that works for you.

**Comment by protoEvangelion** [comment]
@NizarYousri Closing as we have not heard back from you.  Please let us know if you are still experiencing this issue :smile:
