### ISSUE TITLE
Support for configuring labels

### ISSUE THREAD

**Issue by jverkoey** [node-gh/gh#448]
Specifically the create/update/delete endpoints here: https://developer.github.com/v3/issues/labels/#create-a-label

**Comment by jverkoey** [comment]
Open questions: should this be a top-level command group? Should it be a subset of the `repo` group?

**Comment by henvic** [comment]
Yes. It makes sense to be on the subset of the repo group.

**Comment by henvic** [comment]
Are you doing it?
