### ISSUE TITLE
Use API keys by default

### ISSUE THREAD

**Issue by appsforartists** [node-gh/gh#450]
`gh` delegates to the npm `github` module for authentication, which [sends your username and password ](https://github.com/mikedeboer/node-github/blob/master/lib/index.js#L653) as an HTTP header.  That feels insecure.

GitHub has [personal access tokens](https://github.com/settings/tokens) for this purpose, which is what `github` is creating behind-the-scenes.  Can we change the prompt to ask for a token, and completely avoid potentially sending real user credentials over-the-wire?

**Comment by henvic** [comment]
I wish GitHub had something like https://google.com/device (which I intend to use in a project which I am working on).

I am not doing this now, but I might find some time to do so in about 3 weeks (hopefully).

* The ideal case would be using also public / private certificate on the client-side, instead of shared secret (tokens).

**Comment by brennantaylor** [comment]
I was able to use only my username and PAT by leaving the password blank in the `~/.gh.json`.

**Comment by mohhasbias** [comment]
i think it is already supported in the current release. 
we could use github token by fill in it in the ```.gh.json``` file.

there is ```github_token``` property in the file. https://github.com/node-gh/gh/blob/master/default.gh.json#L19

**Comment by mohhasbias** [comment]
i think, asking for ```github_token``` could be used instead of password.

**Comment by protoEvangelion** [comment]
We could offer a list of authentication options using inquirer: https://github.com/SBoudrias/Inquirer.js#prompt-types

The list of options could include what `@octokit/rest` offers: https://github.com/octokit/rest.js#authentication

**Comment by kenshinji** [comment]
> i think it is already supported in the current release.
> we could use github token by fill in it in the `.gh.json` file.
> 
> there is `github_token` property in the file. https://github.com/node-gh/gh/blob/master/default.gh.json#L19

@mohhasbias Are you sure about that? This is what I got when I was using personal access token for accessing.

<img width="1039" alt="Screenshot 2019-05-08 at 10 09 03 AM" src="https://user-images.githubusercontent.com/1403893/57344316-560a2e00-7179-11e9-884c-d6743ae68921.png">

**Comment by protoEvangelion** [comment]
@kenshinji you can generate a personal access token yourself here: https://github.com/settings/tokens/new

Add these scopes:

![image](https://user-images.githubusercontent.com/20076677/57386725-cc069900-7169-11e9-9cca-d846e271855e.png)

And then add to your `~/.gh.json`

```
    "github_token": "yourtoken",
    "github_user": "yourusername",
```

This will allow you to bypass the prompt which is just a convenience method. All we do is generate the personal token and store it for you automatically. Please let me know if you have any issues with that.

I'm closing this for now as we will still offer the convenience method of generating the personal token for you.
