### ISSUE TITLE
Ability to see PR status check

### ISSUE THREAD

**Issue by brennantaylor** [node-gh/gh#459]
Most of our repos run some form of automated check. Would be nice to see if the PR is passed/failed/pending.

In particular I am trying to collect statistics on our various checks. So if there are multiple ones seeing the status of each would be helpful.

**Comment by drselump14** [comment]
@brennantaylor you can see the branch status ( jenkins, test status  , etc) using command 

`gh pr --info <pull-request-number>`

#305

**Comment by protoEvangelion** [comment]
@brennantaylor Does this work for you? If it does not please let me know and we can discuss.
