### ISSUE TITLE
fast forward option for merge pull request

### ISSUE THREAD

**Issue by drselump14** [node-gh/gh#465]
thanks for awesome tool!!

I have one question, is there any way to perform merge pull request with no fast forward option like github default? I'm searching for this option but can't find one ..

Any help will be appreciated

**Comment by henvic** [comment]
No. Send me a pull request with a flag for "gh pr" for that and I can merge it and do a new release with the feature asap, if you want it. I always use fast-forward (I just don't use gh for that).

**Comment by drselump14** [comment]
I see. Ok, i will try to implement that

**Comment by henvic** [comment]
Sure. Let me know if you do. It will be a pleasure to merge or help you out with something you need for adding this feature.

I am working around the clock on a new project ([WeDeploy](http://wedeploy.com/)) with other guys behind NodeGH, so it's almost like we were [kind of hit by a bus](https://en.wikipedia.org/wiki/Bus_factor) when you think about feature requests on NodeGH.

**Comment by protoEvangelion** [comment]
@drselump14 Please let me know if any progress was made on this :smile:
