### ISSUE TITLE
Can't open PRs 

### ISSUE THREAD

**Issue by samuelbeek** [node-gh/gh#468]
When using this command 
`gh pr --open "test"` I get the following response: 

```
Opening pull request #test
fatal: Can't open pull request test.
```

This used to work just fine. What to do?

**Comment by henvic** [comment]
It probably can't find the pull request "test" (where I assume "test" is a number, correct?).

Have you moved remotes? If you try with --user foo --repo bar, does it work?

**Comment by henvic** [comment]
@samuelbeek, maybe you want to logout and login again. A coworker had the same issue you had today and this worked out for him. I don't know why, though.

Maybe permissions scopes changed on GitHub or something.

**Comment by samuelbeek** [comment]
That fixed it, thanks!
