### ISSUE TITLE
Allow user and token to be picked up via process.env

### ISSUE THREAD

**Issue by joscha** [node-gh/gh#469]
Currently the only way to configure the credentials is via the `.gh.json` file - I'd like to use `gh` in CI, but not necessarily check in the credentials - is there any easy way to pass the credentials via an environment variable? I searched the code, but couldn't find anything. Would you accept a PR for this?

**Comment by henvic** [comment]
We don't support it. And yes, I am willing to accept a PR.

Related: https://news.ycombinator.com/item?id=8826024

**Comment by protoEvangelion** [comment]
@joscha Please let me know if you made any progress on this.

If you have please let me know and we can work together on it. 

If not no worries :wink:

**Comment by joscha** [comment]
@protoEvangelion sorry, the response on the question came after I started using an alternative, so I won't be adding this feature. Thanks for following up!

**Comment by protoEvangelion** [comment]
@joscha Thanks for the quick response and I am glad you found something that works ;)
