### ISSUE TITLE
Lock issue

### ISSUE THREAD

**Issue by Nowaker** [node-gh/gh#480]
Something like `gh is 123 --lock`

**Comment by protoEvangelion** [comment]
@Nowaker Could you send a PR for this?

I am working on the backlog and it will be a while before I will be able to get to this.

Sounds like a cool feature :smile:

**Comment by protoEvangelion** [comment]
Looks like this can be done cleanly with the newly add octokit api: https://octokit.github.io/rest.js/#octokit-routes-issues-lock

File location to add this would be here: https://github.com/node-gh/gh/blob/8b772f11332260bf4d316a75957a0c6b2805d4db/src/cmds/issue.ts#L118

The approach would be to add a new flag like `--lock`.

And do `if (options.lock)...`

**Comment by protoEvangelion** [comment]
https://github.com/node-gh/gh/pulls

**Comment by protoEvangelion** [comment]
@Nowaker can you give this a go or provide feedback if this meets your needs? https://github.com/node-gh/gh/pull/687

**Comment by Nowaker** [comment]
@protoEvangelion I guess it would had met my need two years ago for sure. That need is long gone with the project I was working on. But still thanks, someone else will find a use for it, yay! 😀

**Comment by protoEvangelion** [comment]
Ha sorry it took so long!
