### ISSUE TITLE
Got "This API can only be accessed with username and password Basic Auth" when trying to login with 2FA token

### ISSUE THREAD

**Issue by adrienjoly** [node-gh/gh#481]
Similar problem to that one: https://github.com/github/hub/issues/965, right after installing `gh` and running it for the first time.

I went ahead and entered my actual creds, as [advised there](https://github.com/github/hub/issues/965#issuecomment-126527025).

`gh` is working for me now that I did this, but I created this issue to let other users know about this process.

**Comment by protoEvangelion** [comment]
@adrienjoly Much appreciated! Thanks for taking the time to help others out :100:
