### ISSUE TITLE
Comment on a submitted pull request

### ISSUE THREAD

**Issue by brandizzi** [node-gh/gh#528]
It would be nice to gh to be able to comment on a pull request it just submitted. Something like this:

    gh pr -s someuser --comment 'Some comment'

This would be useful, for example, to communicate with CI:

    gh pr -s someuser --comment 'ci:test'

Or to mention users:

    gh pr -s someser --comment 'cc @​anotheruser'

**Comment by protoEvangelion** [comment]
@brandizzi Well there are two ways you can accomplish that:

1. If you are **in the process** of submitting the PR you can do:

```
gh pr -s someuser -D "Your comment"
```

**Description** is technically a comment.

2. If you **have already submitted** the PR, you can do:

```
gh pr yourPrNumber -c "Your comment"
```

Does that achieve what you are trying to do?

**Comment by brandizzi** [comment]
Well, not really, for two reasons:

1. Our CI tool does not read the description, only the other comments.
2. Also, I would rather make a generic description of the pull, and add
some other content (such as mentions) in a comment. (There are alternatives
for that, sure, but that'd be nice :) )

If I send a PR for that, would that get merged?

**Comment by protoEvangelion** [comment]
If I understand you correctly, you are trying to add a comment on PR submit correct?

If that is what you are trying to do, please send a PR and I would be happy to work with you on it to get it merged :)

**Comment by protoEvangelion** [comment]
After thinking this through again, I realized you can actually use a hook to add as many comments as you want after the PR has been submitted.

In your `~/.gh.json` file you can adjust the hook to run whatever cmd you want:

```json
        "pull-request": {
            "submit": {
                "before": [],
                "after": [
                    "{{#if options.number}}gh pr {{options.number}} --user {{options.user}} --repo {{options.repo}} --comment 'Pull request submitted to {{submittedLink}}.{{#if options.changes}} [See changes here.]({{compareLink}}){{/if}}'{{/if}}",
                    "gh pr --browser {{options.browser}} --user {{options.submit}} --repo {{options.repo}} --number {{options.submittedPull}}",
                    "{{#if options.number}}gh pr --user {{options.user}} --repo {{options.repo}} {{options.number}} --close{{/if}}"
                ]
            }
        },
```
