### ISSUE TITLE
optionally display label on issues

### ISSUE THREAD

**Issue by zevaverbach** [node-gh/gh#540]
perhaps with `--label`?

**Comment by protoEvangelion** [comment]
Hmm we actually have a flag for that already but it doesn't seem to be working.

Currently I am working on completely refactoring the code base to use GitHub's GraphQL api. I will make sure this works when we release v2.

At my current pace, I am estimating v2 will be release in April 2019. If that is too long for you to wait, I would be happy to merge a PR from you if you can find a fix for this.

**Comment by zevaverbach** [comment]
@protoEvangelion trying to get started on this, and did the steps outlined in [Contributing](https://github.com/node-gh/gh/blob/master/CONTRIBUTING.md), including `npm rm -g gh` and `npm link` of my fork.  However, I can't get any `console.log` or `process.stdout.write` calls to produce stdout output when invoking `gh`.  Pardon my newbness, but do you have any suggestions?

**Comment by protoEvangelion** [comment]
@zevaverbach no problem at all! I am happy to help 😄  Try this:
```
npm uninstall -g gh
npm link
```

Let me know if that works. If not please let me know which file you are trying to log from.

**Comment by zevaverbach** [comment]
@protoEvangelion awesome, thanks!  See #550.

**Comment by protoEvangelion** [comment]
On second thought I think I misread your intent.
Is your goal to run something like: `gh issue --list --label` and it print out the labels for you?

**Comment by protoEvangelion** [comment]
Thanks for the clarification. I think it would be ideal to only show labels in `--detailed` or if the user has specified that they would like labels to show up by default as discussed here: #548
