### ISSUE TITLE
display labels by default, not only in "detailed" mode

### ISSUE THREAD

**Issue by zevaverbach** [node-gh/gh#548]
I suggest that labels are useful to see most of the time, and if #549 is also implemented, they won't take up too much room.

**Comment by protoEvangelion** [comment]
Since users often parse the output of the gh cmds, this would be a breaking change.
What do you think of offering that option in the `~/.gh.json` file.
Something like:
```json
{
  "version": "1.11.4",
  "cmds": {
    "issue": {
      "showLabels": true
    }
  }
```

**Comment by zevaverbach** [comment]
@protoEvangelion I like it.  Want me to do a PR with that?

**Comment by protoEvangelion** [comment]
That would be great! You can add that onto your currently open PR if you would prefer.

**Comment by protoEvangelion** [comment]
Actually since the labels not showing on the `detailed` flag is a separate issue, I went ahead and merged that. So if you could send a new PR that would be great!

**Comment by protoEvangelion** [comment]
Currently labels are showing with the `--detailed` flag. We will revisit adding labels to `gh is` once we begin this #613
