### ISSUE TITLE
display labels on the same line as the issue's title

### ISSUE THREAD

**Issue by zevaverbach** [node-gh/gh#549]
In a similar manner to [`ghi`](https://github.com/stephencelis/ghi).  Nice and color-coded, doesn't take up a ton of room.  If this is implemented, it'd enable #548 without making things too busy.

**Comment by protoEvangelion** [comment]
This is a good idea. I like the way you formatted labels on the `--detailed` flag, so maybe you can do something like that for this & #548.

**Comment by protoEvangelion** [comment]
Currently labels are showing with the --detailed flag.
