### ISSUE TITLE
authentication issues

### ISSUE THREAD

**Issue by artivilla** [node-gh/gh#561]
Attempt:
Trying to view github issues by running `gh is` in a private respository.

Results:
Looked through some other issues and I'm still having this issue:
```
? Enter your two-factor code 883593
{ [Error: {"message":"Must specify two-factor authentication OTP code.","documentation_url":"https://developer.github.com/v3/auth#working-with-two-factor-authentication"}]
  message: '{"message":"Must specify two-factor authentication OTP code.","documentation_url":"https://developer.github.com/v3/auth#working-with-two-factor-authentication"}',
  code: 401 }
```
mac OSX : 10.12.6 (16G1212)
gh@1.12.14

**Comment by protoEvangelion** [comment]
Hey @artivilla I will look into this. In the meantime can you run again with `--verbose` and post the output please? Thanks 😄

**Comment by artivilla** [comment]
Actually, I noticed the token was going to my sms instead. All good, I'll try this out and reopen if I run into any issues.

**Comment by protoEvangelion** [comment]
Thanks for the update @artivilla
