### ISSUE TITLE
node-gh home page shows 404 error in iframe

### ISSUE THREAD

**Issue by ericnewton76** [node-gh/gh#582]
btw, cool project! will `npm install -g node-gh` for sure.

just wanted to let you know...

![image](https://user-images.githubusercontent.com/2211788/47259449-ba80cc80-d477-11e8-8071-3d606a89513f.png)

**Comment by jwu910** [comment]
Bump @protoEvangelion

**Comment by protoEvangelion** [comment]
@ericnewton76 thanks for the heads up!!! `npm i -g gh` by the way 😉 

@jwu910 I think this has to do with the [asciinema](https://asciinema.org/a/3391) link. Wanna take a look on the `gh-pages` branch?

**Comment by jwu910** [comment]
@protoEvangelion 	Already took a look. I think either asciinema deletes files after a certain time, or the original owner deleted the file. Probably will have to re-record something for it.

I used https://github.com/phw/peek on my own projects. Check it out =p

**Comment by jwu910** [comment]
Nice job
