### ISSUE TITLE
Enhancement: Show pull requests list in a nice table

### ISSUE THREAD

**Issue by hamxabaig** [node-gh/gh#589]
Hey there, excellent work by the way. I use it almost every other hour daily. There is one enhancement which can be made. I mostly use it to list opened PRs.

When looking at the PR's list, it seems you have to look around and find the data you need even if its right in front of you. Thats why i think it needs a little bit of redesign?

I was playing with this [table component](https://github.com/jamestalmage/cli-table2) which seems very nice. This is what i came up with:
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/12872177/50107497-b8a76f80-0254-11e9-83e3-222e0ebd568f.png">

I think with a little redesign, its very straight forward and looks nice as compared to this:
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/12872177/50107570-e1c80000-0254-11e9-9f3d-6439d850a588.png">

Right now i'm using this table locally with `gh`, I'll be happy to provide a PR if that makes sense. Oh one more thing, it also supports terminal links using this [terminal-link](https://github.com/sindresorhus/terminal-link) in supported terminals (I use iterm2) which is nice.

**Comment by protoEvangelion** [comment]
Hey @hamxabaig I really like this!

A couple questions first:

1. How does this look when the terminal isn't full width? Does it resize nicely?
2. What are your thoughts on backwards compatibility. I know some GH users have scripts which parse the output of cmds like `gh pr`. Maybe we could add this to the `~/.gh.json` config as a key like `table: true` or `output: 'table'` `output: 'string'`

**Comment by hamxabaig** [comment]
@protoEvangelion 

1. Yep it does, I have given the widths for the columns in % which i then calculate based on the terminal's total columns. The `cli-table2` component then wraps the text if it doesn't fill.
<img width="956" alt="image" src="https://user-images.githubusercontent.com/12872177/50108366-d70e6a80-0256-11e9-8f9a-dfaf15ec51a9.png">

There is some space left on the right side, so if i calculate the widths more accurately. It should be good with responsiveness of the terminal.

2. About this, yes definitely. I was thinking of adding it like that so that people can turn it off and fallback to old list.

**Comment by protoEvangelion** [comment]
Nice! Was there a reason you chose to use `cli-table2` over https://github.com/Automattic/cli-table ?

I just read the cli-table src code which seems really clean/minimal and it appears to have better maintenance. I think it would be a great idea as well to include the terminal link idea as well 👍

One implementation thing to take into account is if the user adds the `--detailed` flag.

That being said I would be happy to merge a PR from you on this. It's a great idea!

Make sure to follow [this](https://github.com/node-gh/gh/blob/master/CONTRIBUTING.md#if-you-want-to-fix-bugs-or-add-new-features-youll-need-to-run-in-development-environment) and let me know if you have any questions in the meantime 😄

**Comment by hamxabaig** [comment]
Yeah, `cli-table2` offers more features. Like new lines wrapping, more flexible columns management. More [advanced options](https://github.com/jamestalmage/cli-table2/blob/master/advanced-usage.md)

About `--detailed` flag, what do you suggest? I think we can show the body of the PR below title in the title column. Or we can render it completely different then the above. Like below:

Title
Body
Author, Time, Status

```
┌───────────────┐
│ greetings     │
├───────────────┤
│ greetings     │
├───────┬───────┤
│ hello │ howdy │
└───────┴───────┘
```

I'll play with it and will check what i come up with.

**Comment by theist** [comment]
Hi!

Just updated my `gh` and the new `gh pr` table format kicked in. Is there an optional parameter to see as it was before this? I have poor sight and keep a big font on the screen. As a result the  previous version was clearer for me and easier to grep.

**Comment by hamxabaig** [comment]
@theist if you put `output: text` in json config file. I think it'll revert back to original text format. https://github.com/hamxabaig/gh/commit/0355a3006f59f25b09be89d874ed6a7dede1fd1d#diff-19fe9f14f395325dacf92342653af099R712

**Comment by theist** [comment]
@hamxabaig Nope, but you at least point me to the right place in the code, it seems the config option to control this now is a boolean called `config.pretty_print` so I was able to revert it back.

Thanks!

**Comment by hamxabaig** [comment]
Ah @theist i remember now, cool you found it!
