### ISSUE TITLE
Add clear success confirmation when deleting gists & repos

### ISSUE THREAD

**Issue by protoEvangelion** [node-gh/gh#602]
We could add a simple success check mark like we do for PR builds that pass

```js
    switch (pull.combinedStatus) {
        case 'success':
            status = logger.colors.green(' ✓')
            break
        case 'failure':
            status = logger.colors.red(' ✗')
            break
    }
```

**Comment by Aaron-K-T-Berry** [comment]
I reckon i can pick this up 👍

**Comment by protoEvangelion** [comment]
All you @Aaron-K-T-Berry ! The two areas to start looking are:
https://github.com/node-gh/gh/blob/master/src/cmds/repo.ts#L146
https://github.com/node-gh/gh/blob/master/src/cmds/gists.ts#L80

Let me know if you could use direction in the meantime.

**Comment by Aaron-K-T-Berry** [comment]
I've added the messages for gists so far but I'm not sure how they should be looking. 

* This is the message for successfully deleting a gist.
   ```
   Successfully deleted gist: 00f0f2e3d42419839b95c026a21dd3bd ✓
   ```
* Choosing not to delete a gist
   ```
   ? Are you sure? This action CANNOT be undone. [y/N] n
   Not deleted. ✗
   ```
* I also updated the error message when attempting to delete a gist
   ```
   Error: Can't delete gist: 00f0f2e3d42419839b95c026a21dd3bd. ✗
    ```

Let me know if this is the right direction and then I can do something similar for the repos. 😀

**Comment by protoEvangelion** [comment]
@Aaron-K-T-Berry I like it. What do you think about adding the check or x to the front of the line so it's clearer if they delete multiple gists at a time with `gh gi --delete 4252321 --delete 4252322
`?

**Comment by Aaron-K-T-Berry** [comment]
Yeah I like it makes it a bit easier to scan through

```
Deleting gist Aaron-K-T-Berry/dd2b781fae167fa5a5e67ece01686e8f
✓ Successfully deleted gist: dd2b781fae167fa5a5e67ece01686e8f
Deleting gist Aaron-K-T-Berry/ebf9ac14204571a0255bfc6cf258fc3e
✓ Successfully deleted gist: ebf9ac14204571a0255bfc6cf258fc3e
```

Also for the error and not deleted message are a little clearer now at a glance.
```
? Are you sure? This action CANNOT be undone. [y/N] n
✗ Not deleted.

Error: ✗ Can't delete gist: f7b3365a6fe447182de1a6ff7ccb6009.
```

**Comment by protoEvangelion** [comment]
Very good! Feel free to add that to repo as well. It looks much better 🎉
