### ISSUE TITLE
`repo --new` fails silently, doesn't work as expected

### ISSUE THREAD

**Issue by zevaverbach** [node-gh/gh#624]
It seems like `gh repo --new` doesn't do anything, but it doesn't report an error or ask for additional arguments.

My expectation is that if you're in a git init'd local repository, `gh repo --new` would create a public repo on Github and add it as "origin" to the local repo, preferably also doing a `set-url` for convenience too.

Would you accept a PR implementing these?  I'd also update the documentation to reflect it, while (if you want) preserving backward compatibility with the current `repo --new` docs.

**Comment by protoEvangelion** [comment]
@zevaverbach thanks for catching that!

If you find the bug, we would be happy to accept a PR for that.

`gh re --new foo --clone` should clone to your current directory and achieve what you are looking for. If this doesn't do what you would like, please let me know 😄

**Comment by protoEvangelion** [comment]
🎉 This PR is included in version 1.17.2 🎉
