### ISSUE TITLE
Listing with ability to specify the date formatting string

### ISSUE THREAD

**Issue by bokchan** [node-gh/gh#625]
In the list views the date is formatted as relative i.e.: 

```bash
> gh is -M 40 -u username -S closed 

Listing closed issues on username/myrepo
#337 One patch @bokchan (a day ago)
.....
#333 Last patch @bokchan (a month ago)
```

The order/formatting of `PR number`, `title`, and `github username` can be manipulated with `sed`, but it could be really nice to be able to specify the **formatting of the date**, .e.g 

```bash
> gh is -M 40 -u bokchan -S closed --date-format%Y-%m-%d

Listing closed issues on bokchan/myrepo
#337 One patch @bokchan (2019-02-10)
.....
#333 Last patch @bokchan (2018-01-10)
```

**Comment by protoEvangelion** [comment]
Hey @bokchan, right now we only have to views: detailed and non detailed. Can you give some examples of what you are looking to print out and not print out?

**Comment by bokchan** [comment]
Hi @protoEvangelion 
First of all, thanks for a great tool! 

The question came up because I wanted to generate a changelog from a milestone which lists the datetime as **relative** 

```bash
> gh is -M 40 -u bokchan -S closed 

Listing closed issues on bokchan/myrepo
#337 One patch @bokchan (a day ago)
.....
#333 Last patch @bokchan (a month ago)
```

The order/formatting of `PR number`, `title`, and `github username` can be manipulated with `sed`, but it could be really nice to be able to specify the **formatting of the date**, .e.g 

```bash
> gh is -M 40 -u bokchan -S closed --date-format%Y-%m-%d

Listing closed issues on bokchan/myrepo
#337 One patch @bokchan (2019-02-10)
.....
#333 Last patch @bokchan (2018-01-10)
```

**Comment by protoEvangelion** [comment]
Thanks for the clarification. So we use moment for our date parsing. Would something like this work for you? https://momentjs.com/docs/#/displaying/format/

**Comment by bokchan** [comment]
> Thanks for the clarification. So we use moment for our date parsing. Would something like this work for you? https://momentjs.com/docs/#/displaying/format/

If you mean the formatting capabilities offered by `momentjs`, then yes that would be more sufficient :) 

I will change the title and description to make the issue clearer

**Comment by protoEvangelion** [comment]
@bokchan I just added the ability to pass in a formatter like `gh is --date "ddd, hA"` here: https://github.com/node-gh/gh/pull/626

It should also now work for all other list based cmds.

You can check it out by forking, cloning, then running:

```
gh pr 626 -u node-gh
```

and following instructions [here](https://github.com/protoEvangelion/gh/blob/b2b11f25d8e5e57c97b8eaaa16bcfbd748f443b4/CONTRIBUTING.md#building) to build and link it. Let me know if that achieves what you are looking for 😉
