### ISSUE TITLE
The PR status display does not support the "pending" and "error" statuses

### ISSUE THREAD

**Issue by drewbrokke** [node-gh/gh#628]
According to [Github's documentation](https://developer.github.com/v3/repos/statuses/#statuses), there are 4 possible statuses that a pull request can be in (marked by CI integration, for example):

- error
- failure
- pending
- success

Right now, `gh` only supports "failure" and "success", but this is misleading when quickly glancing over the list of pull requests.  `gh` should be able to display each possible state.

**Comment by protoEvangelion** [comment]
When you say "support", are you referring to the green check mark & red x that are printed out when listing PRs?

**Comment by drewbrokke** [comment]
yes exactly, thanks for clarifying :)
