### ISSUE TITLE
Add new PR Draft feature

### ISSUE THREAD

**Issue by protoEvangelion** [node-gh/gh#645]
https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by bryceosterhaus** [comment]
+1

**Comment by tranvietanh1991** [comment]
+1

**Comment by protoEvangelion** [comment]
@mdelapenya thanks for getting the ball rolling on this! I am about to merge a PR that includes the latest Octokit. So you can use this endpoint: https://octokit.github.io/rest.js/#octokit-routes-pulls-create

**Comment by mdelapenya** [comment]
Well, I'm not a nodejs developer at all, so sorry for my ugly code!
