### ISSUE TITLE
Add tilde (~) to all packages in package.json so users get patch updates

### ISSUE THREAD

**Issue by protoEvangelion** [node-gh/gh#689]
Currently most of our packages are listed as exact version so if a security fix or small bug fix comes out that is a patch, the user will not get that update unless we do a new release.

This work will involve removing any prefix from a version like `^` and adding prefix `~` to each package along with running `npm install`.

Here is how the `~` matching will work using https://semver.npmjs.com/:

![image](https://user-images.githubusercontent.com/20076677/66152653-cacd8100-e5ce-11e9-8808-e78d73e05376.png)

**Comment by gabrieluizramos** [comment]
I can work at this :)

**Comment by protoEvangelion** [comment]
All you @gabrieluizramos let me know if you have questions in the meantime :)

**Comment by gabrieluizramos** [comment]
@protoEvangelion Sure! Thank you, I've already opened the PR 😄
