### ISSUE TITLE
repo --new should use the local repo's dirname by default

### ISSUE THREAD

**Issue by zevaverbach** [node-gh/gh#695]
**Describe the solution you'd like**
`repo --new --type private`, for example, when executed in a local repo called `repo`, would create a new private repo with the name `repo`.

Would render #694 moot.

Would you accept a PR implementing this?

**Comment by protoEvangelion** [comment]
Hmm aren't we already doing that? https://github.com/node-gh/gh/blob/master/src/cmds/repo.ts#L541

**Comment by zevaverbach** [comment]
I'm afraid not! Just upgraded to 2.1.0 and `gh repo --new --type private` and it created [this repo](https://github.com/zevaverbach/--type), which is called `--type` and is public.

**Comment by protoEvangelion** [comment]
Does this work for you? `gh re --new foo --init --type private`

**Comment by zevaverbach** [comment]
The `--init` isn't required, and yes, that does work, but it doesn't resolve this issue (naming the repo according to the root dir name).

**Comment by protoEvangelion** [comment]
I see. So it sounds like we are forcing whatever comes after `--new` to be the repo name. What you want to do makes sense then.

Go for it and please let me know how I can help 👍

**Comment by zevaverbach** [comment]
👍 Will do. Any thoughts on doing #696 simultaneously?

**Comment by protoEvangelion** [comment]
I'm fine with it being one PR unless you prefer to do it in 2 :)

**Comment by protoEvangelion** [comment]
Sorry about that...this is getting auto closed by some script I have 😑

**Comment by protoEvangelion** [comment]
@zevaverbach I've been thinking about this some more and it seems to be fundamentally a parser issue.

Our parser (nopt) isn't "smart" in that if you pass two flags one right after the other `--foo --bar` the parsed options will be `{ foo: '--bar'}`.

I've been wanting to change option parsers for a while now, but you may to get around this by checking if the value in `new` is a known flag. If it is, we can fallback to the local dir's name.

**Comment by protoEvangelion** [comment]
Doing some further research, it looks like nopt resolved this exact issue in it's latest version v4:

![image](https://user-images.githubusercontent.com/20076677/68266989-969e1380-0005-11ea-86aa-9eee2b3f9ccc.png)

The version we are using:

![image](https://user-images.githubusercontent.com/20076677/68266977-8e45d880-0005-11ea-80aa-e62179fa106b.png)

Updating, could be the proper resolution to this ;)

**Comment by protoEvangelion** [comment]
@zevaverbach did you have something in the works already?

**Comment by zevaverbach** [comment]
Not yet, sorry!

**Comment by protoEvangelion** [comment]
That's OK. I will update nopt to see if that fixes the issue 👍
