### ISSUE TITLE
When creating a remote repo with --new, do "git remote add origin" automatically

### ISSUE THREAD

**Issue by zevaverbach** [node-gh/gh#696]
**Describe the solution you'd like**
A one-liner of (see #695) `gh --new` that creates a repository on GitHub, in this case named after the local repo's dirname, *and* adds the new repository as a remote called `origin`.

**Comment by protoEvangelion** [comment]
This sounds like a sensible default 👍

**Comment by protoEvangelion** [comment]
@zevaverbach try `gh re --new --clone --init` or without `--init`
