### ISSUE TITLE
Cannot use Forward

### ISSUE THREAD

**Issue by inacionery** [node-gh/gh#709]
**Version number**
Master

**To Reproduce**

gh pr 236 -fwd brianchandotcom                                                                                                                         
Forwarding pull request #236 to @brianchandotcom
Total 0 (delta 0), reused 0 (delta 0)
remote:
remote: Create a pull request for 'pr-236' on GitHub by visiting:
remote:      https://github.com/inacionery/liferay-portal/pull/new/pr-236
remote:
To github.com:inacionery/liferay-portal.git
 * [new branch]                pr-236 -> pr-236
Error: Can't forward pull request 236 to brianchandotcom.
Error: Error submitting PR
HttpError: 'body' cannot be null
    at _fwdHandler (/usr/local/lib/node_modules/gh/lib/cmds/pull-request.js:731:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by protoEvangelion** [comment]
Thanks for reporting @inacionery I will take a look soon.

**Comment by protoEvangelion** [comment]
all-contributors add @inacionery bug

**Comment by protoEvangelion** [comment]
@all-contributors add @inacionery bug

**Comment by inacionery** [comment]
@protoEvangelion thanks a lot! :D
