### ISSUE TITLE
Validation error when doing gh pr -s <user>

### ISSUE THREAD

**Issue by allen-ziegenfus** [node-gh/gh#755]
**Version number**
In which version does the bug appear? 2.8.4

**Describe the bug**
If i do `gh pr -s <user>` I get a Http Error Validation failed response and the pr is not submitted

**To Reproduce**

1. Run `gh pr -s <user>`
2. See error Http Error: Validation failed

**Expected behavior**
PR is submitted

**Additional context**
Downgrading to 2.8.3 fixes the issue

**Comment by protoEvangelion** [comment]
Hey what's up @allen-ziegenfus !!!

Does adding "use_editor": false to your `~/.gh.json` fix it?

Gh will try to open your editor if you don't supply a title or a description. I'm guessing it's failing in this process if it doesn't have proper permissions to create temp files.

**Comment by allen-ziegenfus** [comment]
hey @protoEvangelion  nice to see you!!! :rocket: 

it looks like that does fix it

strangely enough this did work without that pre 2.8.4!

**Comment by protoEvangelion** [comment]
Awesome glad to hear it! Let me know if you have any more issues with that 👍

**Comment by allen-ziegenfus** [comment]
it's working like a champ thanks man! :rocket:
