### ISSUE TITLE
`gh pr --submit` not working

### ISSUE THREAD

**Issue by Woollim** [node-gh/gh#759]
**Version number**
2.8.5

**Describe the bug**
`gh pr --submit` not working

**To Reproduce**
1. move to PR request branch
2. enter `gh pr --submit Woollim`
3. see error

**Expected behavior**
PR Submit Success

**Screenshots**
![이미지 2020  2  10  오후 1 42](https://user-images.githubusercontent.com/24635384/74122351-37582c80-4c0e-11ea-8a45-c56286c095ec.jpg)

**Additional context**

**Comment by Woollim** [comment]
This issue is solved
The reason of this issue is that i didn't specify a `Repository Owner`
So you should write in the following grammar.
```
gh pr --sumit [Repository Owner or Organization]
```

thanks 😊

**Comment by protoEvangelion** [comment]
Thanks for the suggestion @Woollim adding that to the readme now :)
