### ISSUE TITLE
deprecated library warning (Request@2.88.2)

### ISSUE THREAD

**Issue by cokia** [node-gh/gh#761]
**Version number**
2.8.5
**Describe the bug**
deprecated library "request@2.88.2"
**To Reproduce**

1. Run Cmd 'npm install -g gh'
2. See warning `npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142`

**Expected behavior**
deprecated library is dangerous.

**Screenshots**
![image](https://user-images.githubusercontent.com/24792377/74590540-aab8ce80-5052-11ea-9718-8feb3bb8f591.png)

**Additional context**

**Comment by Lisiadito** [comment]
Yes request is deprecated officially since the 11th of February this year.
It should be replaced by an alternative. They list some alternatives in this issue [right here](https://github.com/request/request/issues/3143)

**Comment by protoEvangelion** [comment]
Thanks for the heads up! I am planning on removing plugins in favor of hooks which will remove the need for this package completely so closing for now.
